### ISSUE TITLE
Add Editor plugin support

### ISSUE THREAD

**Issue by nt1m** [nt1m/devtools-prototyper#11]
Maybe support for Emmet or Zen-coding ?

**Comment by mdibaiee** [comment]
I think we can close this now. Also #14.

**Comment by nt1m** [comment]
@mdibaiee Indeed.
About other languages, apparently Emmet supports CSS too (but I'm unsure how it works with CSS). About JS, I haven't heard of something like so.

**Comment by mdibaiee** [comment]
I have used Emmet for CSS in the past, I'm not a fan of these kind of tools, but that's pretty cool, I'm currently working on settings panel, will enable Emmet for CSS if you agree.

**Comment by nt1m** [comment]
@mdibaiee Awesome ! Yeah, I'm fine for enabling Emmet for CSS.
