### ISSUE TITLE
Investigate moving elements hiding partially code area

### ISSUE THREAD

**Issue by nt1m** [nt1m/devtools-prototyper#17]
The run button, or the code-box labels for example.

**Comment by mdibaiee** [comment]
I think a left-side toolbar should be fine. It's also extendable so we can add more actions/options later if needed.

My idea is an icon-only toolbar like Photoshop/Codewars, what do you think? If you agree I'll make it.

**Comment by nt1m** [comment]
@mdibaiee The left sidebar is a great idea ! Hiding the code-box labels when focusing the box is a good idea to me too
