### ISSUE TITLE
Ability to toggle editors

### ISSUE THREAD

**Issue by mdibaiee** [nt1m/devtools-prototyper#22]
Sometimes I only want to write JS, it would be great if I could show/hide editors like in JSBin.

**Comment by mdibaiee** [comment]
I've implemented this, but you've used `--theme-background-selection` for the run button in order to highlight it, that's what I want to do to indicate an enabled/disabled editor. It may cause confusion to have both, may I revert your changes to run button? Any ideas?

![preview](https://i.imgur.com/YOSpSe9.png)

Thanks

**Comment by nt1m** [comment]
Nice work ! Feel free to remove the highlight from the run button, it was just to make the run button stand out from the other ones.
Also, it would be nice if the toggle buttons were stick to the bottom of the sidebar (you can use a flexbox spacer to do that).
