### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by mdibaiee** [nt1m/devtools-prototyper#34]
The code has become bloated, I think we can refactor the code, decreasing the size and increasing readability.

Might take a look into this later myself :+1:

**Comment by nt1m** [comment]
Totally agree with this !
Ideas to solve this : 
- Improve DOM creation code (wrapper functions/use React ?)
- Move some functionality into separate files
- remove not-yet functioning code (highlighter stuff)
- Reorganize functions (getBlobURL is only used by the export menu , so we can move the code there)

I've usually use this for my other projects : 
<pre>
function Element(tagName, attributes) {
  var element = this.doc.createElement(tagName);
  for (var attr in attributes) {
  if (attr == "style" || attr == "css") {
    element.style = attributes[attr]
    continue;
  }
  if (attr == "content") {
    element.innerHTML = attributes.content;
    continue;
  }
  if (attr.startsWith("on")) {
    element.addEventListener(attr.replace("on",""), attributes[attr]);
    continue;
  }
  if (attr == "container") {
    attributes.container.appendChild(element);
    continue;
  }
  element.setAttribute(attr, attributes[attr]);
  }
  return element;
}
</pre>

**Comment by nt1m** [comment]
Starting refactoring things a bit, some of the code is still a bit ugly, but I wanted to get a first cut at this stuff quickly.

My plan is to move out each view (toolbar, editors) as a module. I've started with the library and settings code, I'd ideally move towards a MVC architecture if I have enough time.

**Comment by mdibaiee** [comment]
Are we going to close this, too?

**Comment by nt1m** [comment]
@mdibaiee Yep
