### ISSUE TITLE
Add shortcut to open console

### ISSUE THREAD

**Issue by Kolorbon** [nt1m/devtools-prototyper#48]
It would be nice, if like in all the other devtools tabs you could open the console with the escape key.

**Comment by mdibaiee** [comment]
Good idea, I'll take a look to see if it's possible or not.

**Comment by nt1m** [comment]
Seems like our keybindings are overriding the default ones. Not sure if we need to reimplement them, or if there's a way to not override default keybindings

**Comment by mdibaiee** [comment]
Oh yeah, opening Settings panel and then pressing Esc works, I think CodeMirror is taking the "Esc" key. But the "Debugger" panel works flawlessly even when focusing CodeMirror.

**Comment by mdibaiee** [comment]
I see, we need a `Esc: false` in extraKeys when initializing editors, going to fix it.

**Comment by nt1m** [comment]
@mdibaiee Thanks for the quick fix !

**Comment by mdibaiee** [comment]
:rose: :hand:
