### ISSUE TITLE
Fix Cmd/Ctrl+S keybinding

### ISSUE THREAD

**Issue by nt1m** [nt1m/devtools-prototyper#49]
It should open the export menu. @mdibaiee Any chance you can take a look at this ? Thanks :)

**Comment by mdibaiee** [comment]
Sure, but today I tried installing the add-on after writing some code for this, and now I get:

```
1441102389281	addons.xpi	WARN	Error loading bootstrap.js for devtools-prototyper@tim-addons.com: TypeError: require is not a function (resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/mahdi/Library/Application%20Support/Firefox/Profiles/j6fmkdi9.default-1437330475598/extensions/devtools-prototyper@tim-addons.com.xpi!/bootstrap.js:8:18) JS Stack trace: @resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///Users/mahdi/Library/Application%20Support/Firefox/Profiles/j6fmkdi9.default-1437330475598/extensions/devtools-prototyper@bootstrap.js:8:18 < @XPIProvider.jsm:4552:1 < XPI_loadBootstrapScope@XPIProvider.jsm:4552:7 < XPI_callBootstrapMethod@XPIProvider.jsm:4627:1 < AI_startInstall/<@XPIProvider.jsm:6046:1
```

**Comment by nt1m** [comment]
@mdibaiee Must be my "modernize bootstrap.js" commit. What channel are you using ? The installation works fine on Nightly for me.
As a temporary workaround, you could rollback to the older bootstrap.js and panel.js files.

**Comment by mdibaiee** [comment]
Nightly 42.0a1 (2015-08-03), I will update my Firefox today.

**Comment by nt1m** [comment]
@mdibaiee So older nightlies don't support this : 
`const {require, loader} = Cu.import("resource://gre/modules/devtools/Loader.jsm", {});`
I'll have to rollback to older methods then.

**Comment by nt1m** [comment]
@mdibaiee Alright, you shouldn't get issues with https://github.com/nt1m/devtools-prototyper/commit/1da5bfdc615697e617213c09f307b715f2e4acb3 and https://github.com/nt1m/devtools-prototyper/commit/1b9a31fd95964d098d062ff22e3be765f62e6466 now.

**Comment by nt1m** [comment]
Thanks for the fix !

**Comment by mdibaiee** [comment]
@nt1m: :rose: :hand:
