### ISSUE TITLE
Add a indicator on tabs that have DevTools Prototyper launched

### ISSUE THREAD

**Issue by nt1m** [nt1m/devtools-prototyper#52]
I sometimes lose track of where I've opened DevTools Prototyper, the only indicator I have is the tab title, but it's not very easy to spot, and goes away if I navigate away to check some MDN doc before going back to my prototype.

**Comment by mdibaiee** [comment]
What do you think about a favicon? Probably the prototyper logo?

**Comment by nt1m** [comment]
@mdibaiee A favicon could work, but I'd like an indicator that shows up even if you haven't ran the prototype yet, this is a common use case for me, I usually spend a lot of time writing my prototype before actually running it. It's not uncommon that I switch tabs to consult MDN or any other site. The prototyper icon should work, possibly layed out like this: http://people.mozilla.org/~shorlander/mockups/devTools/DevFox/ (green icon).

Or perhaps this should be a separate add-on that shows a generic toolbox icon.

**Comment by mdibaiee** [comment]
This is great, isn't this going to be built into Firefox? I think it's really useful, I usually lose track of where I opened the devtools.

I think having this as a separate add-on would be better if it's not going to be built-in.
