### ISSUE TITLE
Errors from prototyper code don't appear in the console

### ISSUE THREAD

**Issue by mdibaiee** [nt1m/devtools-prototyper#54]
It seems like using `console.log` doesn't work inside prototyper (it doesn't even log to Browser Console, it shouldn't).

Can you confirm this @nt1m?

**Comment by nt1m** [comment]
@mdibaiee I'll need to fix DT prototyper first since it's broken in Nightly.

**Comment by nt1m** [comment]
@mdibaiee Yes, I can confirm. Something is causing the logging apis to be disabled: "The Web Console logging API (console.log, console.info, console.warn, console.error) has been disabled by a script on this page."

**Comment by nures** [comment]
it seems that this bug is not present in newer versions of firefox

**Comment by nt1m** [comment]
@nures, the console API seems to work, but errors are still not shown:
if you type:
`I("hello")` in the JS, you should get `I is undefined`, but instead nothing happens.
