### ISSUE TITLE
DevTools Prototyper doesn't show up in devtools

### ISSUE THREAD

**Issue by freMea** [nt1m/devtools-prototyper#59]
I just install to try this addon and can **NOT** see it in devtools

**### Setup**

- Firefox 49.0
- DevTools Prototyper 4.1.1
- Add-on Compatibility Reporter 2.2.1

nothing else in a fresh test profile

**### Steps**

1. New fresh profile
2. Install  **Add-on Compatibility Reporter** addon 
3. It reports **Multiprocess is enabled**
4. Install  **DevTools Prototyper** addon 
5. Restart Firefox
6. **Add-on Compatibility Reporter** reports now **Multiprocess is NOT enabled** although the addon manager reports **DevTools Prototyper** and **Add-on Compatibility Reporter** are **Compatible with multiprocess**
7. Browse any web page and open devtools
8. I can NOT see the Prototyper button as shown in image:

[https://addons.cdn.mozilla.net/user-media/previews/full/164/164792.png](url)

Am I doing wrong or should I enable other thing?

**Comment by nt1m** [comment]
Thanks for reporting! I'll grab a look.

**Comment by nt1m** [comment]
One thing you can try is going into the developer tools settings and check whether you see "Prototyper". Although it should appear automatically.

**Comment by freMea** [comment]
There is no other options than the default one in devtools. 

    Le Mercredi 21 septembre 2016 8h44, Tim Nguyen <notifications@github.com> a écrit :
 
 

 One thing you can try is going into the developer tools settings and check whether you see "Prototyper". Although it should appear automatically.—

**Comment by nt1m** [comment]
The problem is fixed in version 4.1.2: https://addons.mozilla.org/en-US/firefox/addon/devtools-prototyper/versions/?page=1#version-4.1.2
Merci d'avoir rapporté le problème!

**Comment by freMea** [comment]
Nickel!

Du coup, il y a le même souci avec **Stylish Developer Tool**. Ce sera peut-être la même correction à faire.

**Comment by nt1m** [comment]
@freMea il faut installer Stylish au cas ou tu l'aurais pas fait: https://addons.mozilla.org/fr/firefox/addon/stylish/?src=search

**Comment by freMea** [comment]
Oui, bien sûr. Je ne suis pas un n00b. '^^
Je pense Stylish devtools 1.0.8 partage le même code que Prototyper 4.1.1 pour ajouter l’outil aux devtools et souffre donc du même bug, c'est à dire absent des outils devtools disponibles, y compris dans les options. C'est en tout le cas sur mon setup : Firefox 49.0 x64, Win 10 x64. 

    Le Jeudi 22 septembre 2016 9h30, Tim Nguyen <notifications@github.com> a écrit :
 
 

 @freMea il faut installer Stylish au cas ou tu l'aurais pas fait: https://addons.mozilla.org/fr/firefox/addon/stylish/?src=search—
