### ISSUE TITLE
Allow running Prototyper to be independant from other devtools

### ISSUE THREAD

**Issue by mikhoul** [nt1m/devtools-prototyper#60]
Hi and tahnks for this little gem. :octocat: 

When we are in the devtools prototyper tab  and pressing the Play/Run button it would useful if we have some way to going back to the initial page for the other devtools instead of having the Inspector inspecting the output of our code.

Something like having 2 modes, one with all the devtools devoted to the prototype and a second mode where other devtools apart from prototype stay with the original page.

Best Regards :smile_cat:

**Comment by nt1m** [comment]
@mikhoul Doing a mode exactly like that is tricky, since the prototyper is very tied to the developer tools.

Right now, prototyper can run in its own tab: chrome://devtools-prototyper/content/panel.html which might be handy for your usecase.

**Comment by mikhoul** [comment]
Thanks ! :octocat:
