### ISSUE TITLE
Emmet doesn't work

### ISSUE THREAD

**Issue by dehghani-mehdi** [nt1m/devtools-prototyper#61]
Hi,

First of all, awesome idea for add-on, just keep it up!

I'm using FF v51, also just installed your add-on, I saw setting section, Enable Emmet is marked, but it doesn't work.

Take care,
Mehdi

**Comment by nt1m** [comment]
Right now, the hotkey is Ctrl/Cmd+E for emmet, not "Enter". Can you check if that works ?

I agree the Enter key should work though.

**Comment by dehghani-mehdi** [comment]
I just installed the `prototyper` on FF Beta (52.0b5), but Prototyper tab doesn't appears in Dev tools. _yesterday I installed on FF v51.x_

**Comment by nt1m** [comment]
@dehghani-mehdi Can you try with version 4.5.1: https://addons.mozilla.org/en-US/firefox/addon/devtools-prototyper/versions/ ? Thanks !

**Comment by dehghani-mehdi** [comment]
I just tired & it works, the Ctrl+E also did its job, but would be great if you add `Tab` support too.

**Comment by nt1m** [comment]
@dehghani-mehdi Filed #62
