### ISSUE TITLE
Trouble installing

### ISSUE THREAD

**Issue by jsantell** [nt1m/devtools-prototyper#9]
Worked on a profile where I didn't have e10s on at any point, and fails on one where I did use that.

On first install, getting this message
![http://i.imgur.com/O1x3Rmy.png](http://i.imgur.com/O1x3Rmy.png)

Looks like some issue with bootstrapper starting up
![http://i.imgur.com/Q6LoxTt.png](http://i.imgur.com/Q6LoxTt.png)

Maybe related to #4, but not sure. This is a great addon, though :D :metal:

**Comment by nt1m** [comment]
Seems like most of the recent addon installation changes should fix this. e10s is also much more stable now. Closing, feel free to reopen if you can still reproduce.
